Repository danielcaldas/react-d3-graph, pull requests merged in 2020-10, with the labels that each got.

#381 Don't throw error when there are no nodes
  src/components/graph/graph.helper.js
  test/graph/graph.helper.spec.js
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, priority normal

#377 Fixing graph reset
  src/components/graph/Graph.jsx
  src/components/graph/graph.helper.js
Labels: hacktoberfest-accepted

#385 feature: expose node information to node related callbacks
  sandbox/Sandbox.jsx
  src/components/graph/Graph.jsx
Labels: Hacktoberfest, documentation, enhancement, hacktoberfest-accepted
